apiVersion: v1
kind: Pod
metadata:
  name: pod-test-1
spec:
  restartPolicy: Never

  containers:
  - name: int-container
    image: docker.io/cecilia7717/cloud@sha256:00538b5d37a9c96982428d07cce615da586530f6a1819a186b0b4cb3c7775064
    command: ["/bin/sh", "-c"]
    args:
    - >
      wget -O MODEL.zip --no-check-certificate -r 'https://drive.google.com/uc?export=download&id=1yBy3_4j8PTEnAl5uSSv5HOwzvb4nsugf' &&
      wget -O SCRIPTS.zip --no-check-certificate -r 'https://drive.google.com/uc?export=download&id=1nd8FPBGqtIfOI9Cje4-US45pPfKAyWMr' &&
      pip install gdown &&
      gdown 1GfZ8m516QhZtTrmFFGwHY844RiS9iVjv -O quantized_loss_landscape.zip &&
      conda install -y -c conda-forge onnxoptimizer==0.3.13 onnx==1.15.0 &&
      apt-get update && apt-get install -y unzip &&
      pip install pytorch_lightning matplotlib pyhessian scipy &&
      pip install git+https://github.com/fra31/auto-attack &&
      unzip SCRIPTS.zip &&
      unzip MODEL.zip &&
      unzip quantized_loss_landscape &&
      gdown 'https://drive.google.com/uc?id=1-utul7btK0Mtx2iMglJWGfGjSzYf7qGk' -O PyLandscape.zip && 
      unzip PyLandscape.zip &&
      export PYTHONPATH=/:/PyLandscape &&
      python SCRIPTS/test_normal.py eval --model ags_tiny_unet_50k --resume_from "/pvc/output-alcd-cloud-2/ags_tiny_unet_50k_backend-None-1_20260104-205406/best_checkpoint_60_test_F1=0.8238.pt" --data_path /pvc/ --csv_paths.train "/pvc/train.csv" --csv_paths.test "/pvc/valid.csv"  >> test.txt 2>&1 &&
      cp test.txt /pvc/test_2_0.txt &&
      sleep infinity

    volumeMounts:
    - mountPath: /pvc
      name: pvc
    - mountPath: /dev/shm
      name: dshm

    resources:
      limits:
        cpu: "8"
        memory: 16Gi
        nvidia.com/gpu: "1"
      requests:
        cpu: "8"
        memory: 16Gi
        nvidia.com/gpu: "1"

    securityContext:
      capabilities:
        add: ["IPC_LOCK"]

  volumes:
  - name: pvc
    persistentVolumeClaim:
      claimName: pvc
  - name: dshm
    emptyDir:
      medium: Memory
      sizeLimit: 16Gi

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nvidia.com/gpu.product
            operator: In
            values:
            - NVIDIA-GeForce-RTX-3090
