apiVersion: v1
kind: Pod
metadata:
  name: pod-8
spec:
  restartPolicy: Never

  containers:
  - name: int-container
    image: docker.io/cecilia7717/cloud@sha256:00538b5d37a9c96982428d07cce615da586530f6a1819a186b0b4cb3c7775064
    command: ["/bin/sh", "-c"]
    args:
    - >
      set -e &&
      wget -O MODEL.zip --no-check-certificate -r 'https://drive.google.com/uc?export=download&id=1yBy3_4j8PTEnAl5uSSv5HOwzvb4nsugf' &&
      wget -O SCRIPTS.zip --no-check-certificate -r 'https://drive.google.com/uc?export=download&id=1nd8FPBGqtIfOI9Cje4-US45pPfKAyWMr' &&
      pip install gdown &&
      gdown 1GfZ8m516QhZtTrmFFGwHY844RiS9iVjv -O quantized_loss_landscape.zip &&
      conda install -y -c conda-forge onnxoptimizer==0.3.13 onnx==1.15.0 &&
      apt-get update && apt-get install -y unzip &&
      pip install pytorch_lightning matplotlib pyhessian scipy &&
      pip install git+https://github.com/fra31/auto-attack &&
      unzip SCRIPTS.zip &&
      unzip MODEL.zip &&
      unzip quantized_loss_landscape &&
      gdown 'https://drive.google.com/uc?id=1-utul7btK0Mtx2iMglJWGfGjSzYf7qGk' -O PyLandscape.zip && 
      export PYTHONPATH=/:/PyLandscape &&
      python /SCRIPTS/train_quan.py run --model ags_tiny_unet_50k --seed 23456 --quant_config 8 --data_path /pvc >> 8_23456.txt 2>&1 &&
      cp 8_23456.txt /pvc/8_23456.txt &&
      mv output-alcd-cloud-noisy -r /pvc/output-alcd-cloud-8 &&
      echo "Setup complete. Pod is now idle." &&
      sleep infinity

    volumeMounts:
    - mountPath: /pvc
      name: pvc
    - mountPath: /dev/shm
      name: dshm

    resources:
      limits:
        cpu: "8"
        memory: 32Gi
        nvidia.com/gpu: "1"
      requests:
        cpu: "8"
        memory: 32Gi
        nvidia.com/gpu: "1"

    securityContext:
      capabilities:
        add: ["IPC_LOCK"]

  volumes:
  - name: pvc
    persistentVolumeClaim:
      claimName: pvc
  - name: dshm
    emptyDir:
      medium: Memory
      sizeLimit: 16Gi

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nvidia.com/gpu.product
            operator: In
            values:
            - NVIDIA-GeForce-RTX-3090
