apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
  namespace: reliable-nn
spec:
  storageClassName: rook-cephfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1024Gi