apiVersion: batch/v1
kind: Job
metadata:
  name: test-q2-n2
spec:
  ttlSecondsAfterFinished: 0
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: int-container
        image: docker.io/cecilia7717/cloud@sha256:00538b5d37a9c96982428d07cce615da586530f6a1819a186b0b4cb3c7775064
        command: ["/bin/sh", "-c"]
        args:
        - >
          wget -O MODEL.zip --no-check-certificate -r 'https://drive.google.com/uc?export=download&id=1yBy3_4j8PTEnAl5uSSv5HOwzvb4nsugf' &&
          wget -O SCRIPTS.zip --no-check-certificate -r 'https://drive.google.com/uc?export=download&id=1nd8FPBGqtIfOI9Cje4-US45pPfKAyWMr' &&
          pip install gdown &&
          gdown 'https://drive.google.com/uc?id=19D514KNZfPzed7kbFqKiHF5lFu4nw8wU' -O test_multi.bash &&
          gdown 1GfZ8m516QhZtTrmFFGwHY844RiS9iVjv -O quantized_loss_landscape.zip &&
          conda install -y -c conda-forge onnxoptimizer==0.3.13 onnx==1.15.0 &&
          apt-get update && apt-get install -y unzip &&
          pip install pytorch_lightning matplotlib pyhessian scipy &&
          pip install git+https://github.com/fra31/auto-attack &&
          unzip SCRIPTS.zip &&
          unzip MODEL.zip &&
          unzip quantized_loss_landscape &&
          export PYTHONPATH=/root:$PYTHONPATH &&
          chmod +x test_multi.bash &&
          ./test_multi.bash &&          
          sleep 360000
        volumeMounts:
        - mountPath: /pvc
          name: pvc
        - mountPath: /dev/shm
          name: dshm
        resources:
          limits:
            cpu: 4
            memory: 32Gi
            nvidia.com/gpu: "1"
            ephemeral-storage: 624Gi
          requests:
            cpu: 4
            memory: 32Gi
            nvidia.com/gpu: "1"
            ephemeral-storage: 624Gi
        securityContext:
          capabilities:
            add: ["IPC_LOCK"]
      volumes:
        - name: pvc
          persistentVolumeClaim:
            claimName: pvc
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 32Gi
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                - NVIDIA-GeForce-RTX-3090
