apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: examplevol
  namespace: xdr-lab
spec:
  storageClassName: rook-ceph-fs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 30Gi

